# General
confirm_os_window_close 0

# Window
background_opacity 0.86
window_padding_width 3 5
dynamic_background_opacity no
hide_window_decorations yes
startup_session none
background_blur 1

# Scrolling
scrollback_lines 10000
wheel_scroll_multiplier 3.0

# Font
font_family      JetBrains Mono Regular
bold_font        JetBrains Mono Regular
italic_font      JetBrains Mono Regular
bold_italic_font JetBrains Mono Regular
font_size 18.0

# Colors
foreground #fcfcfc
background #212020

# Cursor
cursor_shape beam
cursor_blink_interval 1.0
cursor_stop_blinking_after 0

# Bell
visual_bell_duration 0.0
enable_audio_bell no

# Keyboard shortcuts
map super+shift+t new_os_window
map super+shift+r new_os_window
map super+shift+f toggle_fullscreen
map super+shift+g quit
