#!/bin/bash

entries="⏾ Suspend\n⭮ Reboot\n⏻ Shutdown\n⏻ Logout"

chosen=$(echo -e "$entries" | wofi --dmenu --width=250 --height=200 --prompt="Power Menu")

case $chosen in
    "⏾ Suspend")
        systemctl suspend
        ;;
    "⭮ Reboot")
        systemctl reboot
        ;;
    "⏻ Shutdown")
        systemctl poweroff
        ;;
    "⏻ Logout")
        hyprctl dispatch exit
        ;;
esac